workspace 'DRoutinesWorkSpace.xcworkspace'
project 'DPrepareDemo/DPrepareDemo.xcodeproj'
project 'DWelcomeDemo/DWelcomeDemo.xcodeproj'
project 'DLoginDemo/DLoginDemo.xcodeproj'
project 'DPersonDemo/DPersonDemo.xcodeproj'
project 'DSettingDemo/DSettingDemo.xcodeproj'
project 'DProfileDemo/DProfileDemo.xcodeproj'
project 'DCircleDemo/DCircleDemo.xcodeproj'
project 'DBannerDemo/DBannerDemo.xcodeproj'
project 'DStoreDemo/DStoreDemo.xcodeproj'
project 'DAddressDemo/DAddressDemo.xcodeproj'


platform :ios, '10.0'
use_modular_headers!

source 'https://github.com/StoneStoneStoneWang/DRoutines'
source 'https://github.com/CocoaPods/Specs.git'

target 'DPrepareDemo' do
  
  project 'DPrepareDemo/DPrepareDemo.xcodeproj'
  
  pod 'DSign'
  
  pod 'DRoutinesKit'
  
  pod 'WLReqKit'
  
  pod 'WLBaseViewController/Inner'
  
  pod 'SnapKit'
  
  pod 'RxSwift'
  
  pod 'RxCocoa'
  
  pod 'WLThirdUtil'
  
  pod 'WLComponentView'
  
  pod 'WLBaseResult'
  
  pod 'Kingfisher'
  
  pod 'WLToolsKit/JsonCast'
  
  pod 'DUpload'
  
  pod 'DReq'
  
end

target 'DWelcomeDemo' do
  
  project 'DWelcomeDemo/DWelcomeDemo.xcodeproj'
  
  pod 'DPrepare'
  
  pod 'WLBaseTableView'
  
  pod 'WLBaseViewModel'
  
end
target 'DLoginDemo' do
  
  project 'DLoginDemo/DLoginDemo.xcodeproj'
  
  pod 'DPrepare'
  
  pod 'WLBaseResult'
  
  pod 'WLBaseViewModel'
  
  pod 'RxSwift'
  
  pod 'RxCocoa'
  
  pod 'SnapKit'
  
  pod 'WLToolsKit'
  
  pod 'WLComponentView'
  
  pod 'SnapKit'
  
  pod 'WLThirdUtil/JPush'
  
  pod 'WLThirdUtil/Hud'
  
end

target 'DPersonDemo' do
  
  project 'DPersonDemo/DPersonDemo.xcodeproj'
  
  pod 'DPrepare'
  
  pod 'WLBaseViewController'
  
  pod 'RxSwift'
  
  pod 'RxCocoa'
  
  pod 'WLBaseTableView'
  
  pod 'WLBaseViewModel'
  
  pod 'WLThirdUtil/Hud'
  
  
end

target 'DSettingDemo' do
  
  project 'DSettingDemo/DSettingDemo.xcodeproj'
  
  pod 'DPrepare'
  
  pod 'WLBaseTableView'
  
  pod 'WLBaseViewModel'
  
  pod 'WLBaseResult'
  
  pod 'DLogin/Login/CheckLogin'
  
  pod 'DPerson/Black/Create'
  
end

target 'DProfileDemo' do
  
  project 'DProfileDemo/DProfileDemo.xcodeproj'
  
  pod 'DPrepare'
  
  pod 'WLBaseTableView'
  
  pod 'WLBaseViewModel'
  
  pod 'WLBaseResult'
  
  ## 布局
  pod 'WLComponentView'
  
  pod 'DLogin/Login/TokenInvalid'
  pod 'DSetting/Setting/Create'
  pod 'DPerson/Focus/Create'
  
  pod 'WLToolsKit/DeviceInfo'
  
end

target 'DCircleDemo' do
  
  project 'DCircleDemo/DCircleDemo.xcodeproj'
  
  pod 'ObjectMapper'
  
  pod 'RxDataSources'
  
  pod 'WLBaseViewModel'
  
  pod 'DPrepare'
  
  pod 'WLBaseTableView/RTV'
  
  pod 'WLBaseTableView/BTVC'
  
  pod 'WLThirdUtil/Hud'
  
  pod 'RxCocoa'
  
  pod 'SnapKit'
  
  pod 'WLBaseTableView/ASM'
  
  pod 'WLBaseResult'
  
  pod 'WLToolsKit/JsonCast'
  
  pod 'Kingfisher'
  
  pod 'DLogin/Login/CheckLogin'
  
  pod 'DProfile/UserInfo/VM'
  
  pod 'WLComponentView/TextFeild/NickName'
end

target 'DBannerDemo' do
  
  project 'DBannerDemo/DBannerDemo.xcodeproj'
  
  pod 'DPrepare'
  
  pod 'WLToolsKit'
  
  pod 'Kingfisher'
  
  pod 'SnapKit'
  
  pod 'WLBaseViewModel'
  
  pod 'RxCocoa'
  
  pod 'RxSwift'
  
  pod 'WLBaseTableView'
  
end
target 'DStoreDemo' do
  
  project 'DStoreDemo/DStoreDemo.xcodeproj'
  
  pod 'ObjectMapper'
  
  pod 'RxDataSources'
  
  pod 'WLBaseViewModel'
  
  pod 'DPrepare'
  
  pod 'WLBaseTableView/RTV'
  
  pod 'WLBaseTableView/BTVC'
  
  pod 'WLThirdUtil/Hud'
  
  pod 'RxCocoa'
  
  pod 'SnapKit'
  
  pod 'WLBaseTableView/ASM'
  
  pod 'WLBaseResult'
  
  pod 'WLToolsKit/JsonCast'
  
  pod 'Kingfisher'
  
  pod 'DLogin/Login/CheckLogin'
  
  pod 'DProfile/UserInfo/VM'
  
  pod 'WLComponentView/TextFeild/NickName'
  
  pod 'WLBaseTableView'
  
  pod 'DBanner'
  
end

target 'DAddressDemo' do
  
  project 'DAddressDemo/DAddressDemo.xcodeproj'
  
  pod 'ObjectMapper'
  
  pod 'RxDataSources'
  
  pod 'WLBaseViewModel'
  
  pod 'DPrepare'
  
  pod 'WLBaseTableView/RTV'
  
  pod 'WLBaseTableView/BTVC'
  
  pod 'WLThirdUtil/Hud'
  
  pod 'RxCocoa'
  
  pod 'SnapKit'
  
  pod 'WLBaseTableView'
  
  pod 'WLBaseResult'
  
  pod 'WLToolsKit/JsonCast'
  
  pod 'Kingfisher'
  
  pod 'DLogin/Login/CheckLogin'
  
  pod 'DProfile/UserInfo/VM'
  
  pod 'WLComponentView/TextFeild/NickName'
  
end
